from models.db import db, instance
from models.auth.role import Role
from models.auth.user import User
from models.auth.user_roles import UserRole
from models.clientes.cliente import Cliente
from models.fornecedor.fornecedor import Fornecedor
from models.funcionarios.funcionarios import Funcionarios
from models.produto.produto import Produto
from models.vendas.vendas import Vendas
from models.fornecedor.entrega import Entrega
from models.fornecedor.produtos_fornecedor import ProdutosFornecedor
from models.fornecedor.entrega_fornecedor import EntregaFornecedor
from models.funcionarios.farmaceutico import Farmaceutico
from models.funcionarios.gerente import Gerente
from models.produto.produtos_entrega import ProdutosEntrega
from models.iot.device import Device
from models.iot.sensor import Sensor
from models.iot.microcontroller import Microcontroller
from models.iot.read import Read